# Generated by Django 3.2.6 on 2021-08-09 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='alumnus',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='areaofinterest',
            old_name='user_id',
            new_name='user',
        ),
    ]
